# Generated by Django 5.1.4 on 2024-12-30 16:13

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, verbose_name='uid пользователя'),
        ),
    ]
