# Generated by Django 5.1.4 on 2024-12-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_ad_created_at_alter_ad_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата и время обновления объявления'),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата и время обновления отзыва'),
        ),
    ]
