# Generated by Django 5.1.4 on 2024-12-23 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название товара', max_length=255, verbose_name='Название товара')),
                ('price', models.DecimalField(decimal_places=2, help_text='Укажите цену товара', max_digits=12, verbose_name='Цена товара')),
                ('description', models.TextField(blank=True, help_text='Введите описание товара', null=True, verbose_name='Описание товара')),
                ('created_at', models.DateTimeField(verbose_name='Дата и время создания объявления')),
                ('is_published', models.BooleanField(blank=True, default=False, help_text='Укажите будет ли объявления опубликовано', verbose_name='Публичность объявления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement', to=settings.AUTH_USER_MODEL, verbose_name='Автор объявления')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Введите отзыв', verbose_name='Отзыв')),
                ('created_at', models.DateTimeField(verbose_name='Дата и время создания отзыва')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='announcements.announcement', verbose_name='Объявление')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_written', to=settings.AUTH_USER_MODEL, verbose_name='Автор отзыва')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
